service: phpmyadmin
runtime: php55
api_version: 1
threadsafe: true

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic

handlers:

- url: /(.+\.(ico|jpg|png|gif|woff|ttf))$
  static_files: \1
  upload: (.+\.(ico|jpg|png|gif|woff|ttf))$
  application_readable: true

- url: /(.+\.(htm|html|css|js))$
  static_files: \1
  upload: (.+\.(htm|html|css|js))$
  application_readable: true

- url: /(.+\.php)$
  script: \1
  login: admin

- url: /.*
  script: index.php
  login: admin

env_variables:
    CLOUDSQL_HOST: 'hoge:asia-northeast1:hoge'
    PHPMYADMIN_THEME_DEFAULT: 'metro' # metro/original
